name: Documentation Website Deployment
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Documentation Deployment
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: deploy manpages to website
        env:
          GH_TOKEN: ${{ secrets.GIT_DEPLOY_KEY }}
        run: |
          git config --global user.email "me@patrickwu.space"
          git config --global user.name "Jinming Wu, Patrick"
          git clone --depth 1 https://patrick330602:$GH_TOKEN@github.com/wslutilities/wslutilities.github.io.git website
          cp -f ./CODE_OF_CONDUCT.md ./website/coc.md
          cp -f ./CONTRIBUTING.md ./website/contributing.md
          git --git-dir=./website/.git --work-tree=./website add -A
          git --git-dir=./website/.git --work-tree=./website commit -m "Document update"
          git --git-dir=./website/.git --work-tree=./website push

